# Generated by Django 5.0.6 on 2026-06-20 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_type', models.CharField(max_length=20)),
                ('exception_code', models.CharField(max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assign_to_role', models.CharField(default='analyst', max_length=20)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
