# Generated by Django 5.0.6 on 2026-06-20 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_type', models.CharField(max_length=20)),
                ('exception_code', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('routed', 'Routed'), ('investigating', 'Investigating'), ('pending_approval', 'Pending Approval'), ('resolved', 'Resolved'), ('approved', 'Approved'), ('closed', 'Closed')], default='detected', max_length=30)),
                ('source_record_ids', models.JSONField(default=list)),
                ('amount_difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_difference', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('context', models.JSONField(default=dict)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=100)),
                ('root_cause_code', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
