# Generated by Django 5.0.6 on 2026-06-20 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('exceptions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptioncomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity'),
        ),
        migrations.AddField(
            model_name='exceptioncomment',
            name='exception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exceptions_app.exceptionrecord'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='exception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='exceptions_app.exceptionrecord'),
        ),
    ]
