# Generated by Django 5.0.6 on 2026-06-20 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
