# Generated by Django 5.0.6 on 2026-06-20 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recon_type', models.CharField(choices=[('bank', 'Bank'), ('ap', 'AP'), ('ar', 'AR'), ('gst', 'GST')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('exception_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('narration', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_lines', to='reconciliation.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(default='bank', max_length=30)),
                ('raw_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='reconciliation.batch')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
